import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Debt Daddy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
         integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
        crossorigin="anonymous"></link>
      </Head>
      <main id="mainElem"> {/*linear gradient colorscheme*/}
      <header>
        <section id="sectionOne">
        <div> {/*don't forget about styling and fonts*/}
          <p id="logoName" className="text-left">Debt Daddy</p>
        </div>
        </section>
      </header>
        <body>
      <div id="scroll-container">
        <section id="sectionTwo">
        <div id="texts">
          <div id='borders'>
            <ol>
            <li id="bodyTitle" className='text-center'>Coming Soon!...</li>
            <li id='bodyText' className='text-center'>Thank you for your patience. 
           Currently Debt Daddy will be operating in the state of Montana only. 
            We will be working to expanding into other states as soon as possible. </li>
            </ol>
          </div>
        </div>
        </section>
          <section id="sectionFour">
            <div className='borders2'>
              <h1 className='sectionFour'>Other States Coming Soon...</h1>
              <ol id='stateList'>
                <li>South Dakota</li>
                <li>Missouri</li>
                <li>Oklahoma</li>
                <li>Mississippi</li>
                <li>Kentucky</li>
                <li>Ohio</li>
                <li>Georgia</li>
                <li>South Carolina</li>
                <li>Virginia</li>
                <li>Pennsylvania</li>
                <li>Vermont</li>
                <li>New Hampshire</li>
              </ol>
              <ol id='stateList' className='cali'> California*
                  <li></li>
              </ol>
            </div>
          </section>
        </div>
        </body>
      </main>
      <footer>
        <div id='footer'></div>
      </footer>
    </>
  )
}
